// elixir/native/flux_data/src/lib.rs
// This file will be auto-generated by Rustler mix compile
// For now, this shows the structure

use rustler::{Env, NifResult, Term, Atom};

#[rustler::nif]
pub fn add(a: i64, b: i64) -> i64 {
    a + b
}

fn load(env: Env, _info: Term) -> bool {
    rustler::resource_struct_init!(flux_data::Indicator, env);
    true
}

rustler::init!("Elixir.Flux.Native", [], load: load);
